const en = {
  menu: {
    bottom: 'zh'
  },
  bottom: {
    btmFollow: 'Follow us',
  },
  menu: {
    home: 'home'
  },
  home: {
    homeTitle: 'Unleashing True Web3 Games',
    homeBanner: 'Advocate for a decentralized, immersive gaming platform that employs native encryption and a fully on-chain approach, free from central authority.',
    homeSubscribeBtn: 'Subscribe',
    homeDocs: 'Docs',
    homeTrusted: 'Trusted by',
    homeSupporting: 'Supporting Decentralized Web3 Games:',
    homeSupportingContent: "Cenozoic is a new protocol designed to support the development of Web3 games openly, transparently, and fairly. It enables games to be fully decentralized in the new era, free from a centralized server's control or a god view.",
    homeInteroper: 'Interoperability:',
    homeInteroperContent: 'Cenozoic offers a shared economy and trade layer composed of game stablecoins and governance tokens. The assets in games supported by the protocol are interoperable.',
    homeBuilding: 'Building On-Chain Reputation for Web3 Players:',
    homeBuildingContent: 'Play is Build. Game data generated by players in on-chain games will be permanently stored on the blockchain and showcased in the protocol in the form of achievement NFTs, helping players build their own on-chain reputation.',
    homeCoMpos: 'Composability:',
    homeCoMposContent: "In Cenozoic's on-chain games, the basic rules are constrained, but any player or developer can create new game rules or maps without permission, unleashing true Web3 games.",
    homeTranspraent: 'Transparent and Fair DAO Governance Mechanism:',
    homeTranspraentContent: "Cenozoic is operated using a DAO governance mechanism. All players, developers, and teams holding governance token ZOIC can stake ZOIC to obtain governance rights of the Cenozoic DAO to decide on the protocol's upgrade, modification, and governance issues.",
    homeCenoTit: 'CENO&ZOIC',
    homeGame: 'Game Stablecoin: CENO',
    homeGameContent1: '100 CENO ≈ 1 USDT',
    homeGameContent2: 'CENO is a collateral-backed cryptocurrency used for pricing, payment, and settlement of in-game assets. Users need to stake USDT or USDC to mint corresponding CENO at a 1:100 ratio, and the staking is redeemable.',
    homeGovernance: 'Governance Token and Game Proof-of-Work: ZOIC',
    homeGovernanceContent: 'ZOIC is the governance token of the Cenozoic protocol and the game proof-of-work of players, produced in the form of PoW and rewarded to players.',
    homeVeZOIC: 'veZOIC',
    homeVeZOICTit1: 'You Control Every Decision | Vote-escrowed System',
    homeVeZOICTit2: 'Decide the Direction of the Decision-making Community, Assets, Protocol & Games | Or Sell Your Voting Power in Secondary Markets',
    homeVeZOICContent: "Cenozoic's governance relies on vote-escrowed ZOIC, also known as veZOIC, which can achieve a higher degree of decentralization. By using veZOIC, ZOIC holders can gain a range of features that increase token utility. veZOIC can also reduce the circulating supply of ZOIC to increase token stability and the overall economic system of the protocol.",
    homeVeZOICBtn: 'Please Look forword to',
    homeHowTit: 'How It Works',
    homeDepositsTit: 'Deposit and Mint CENO:',
    homeDepositsContent: 'Deposit your assets to receive game stablecoin CENO, which can be used for games anytime, anywhere. The CENO treasury is public, and everything is transparent.',
    homeEarnTit: 'Earn Game Rewards and Redeem Assets:',
    homeEarnContent: 'When the game ends, burning NFTs can extract CENO in the game and obtain corresponding ZOIC game rewards. Users can burn CENO and ZOIC in proportion to redeem assets in the treasury within the protocol.',
    homeReceiveTit: 'Earn veZOIC to Increase Game Rewards:',
    homeReceiveContent: 'Players can lock their ZOIC to earn veZOIC, which can increase their ZOIC game rewards based on the number of veZOICs held, up to a maximum of 254%.',
    homeAdvantageTit: 'Advantage',
    homeAdvantageLift1: 'Reduces financial risk for players participating in Web3 games: game coins are stablecoins and NFTs are redeemable.',
    homeAdvantageLift2: 'Increases game earnings for players: in addition to in-game CENO gaming profits, players can also earn ZOIC profits and gain governance voting rights in the protocol.',
    homeAdvantageLift3: 'For players:',
    homeAdvantageRight1: 'Developers can guide game rewards towards games they have developed by obtaining veZOIC voting rights, to attract more players to their games.',
    homeAdvantageRight2: 'Footer: Follow Us',
  }
}


export default en